ProjectAlita/AlitaUI

- src/components/HeaderSplitButton.jsx
- src/components/Icons/ArrowDownIcon.jsx
- src/components/Icons/PlusIcon.jsx
- src/components/NavBar.jsx
- src/components/NotificationButton.jsx
- src/components/SearchPanel.jsx
- src/components/SideBar.jsx
> feat: header split button

- .eslintrc.cjs
- package-lock.json
- package.json
- src/App.jsx
- src/MainTheme.js
- src/components/BasicAccordion.jsx
- src/components/HeaderSplitButton.jsx
- src/components/NavBar.jsx
- src/components/NotificationButton.jsx
- src/components/SideBar.jsx
- src/components/StyledLabel.jsx
- src/components/StyledTabs.jsx
- src/constants/constants.js
- src/pages/PromptDetail/EditPrompt.jsx
- src/pages/PromptList/Categories.jsx
- src/pages/PromptList/TrendingAuthors.jsx
- vite.config.js
1. add the modal
2. add config changes to fix errors after latest code merges
3. introduce "styled" as a global vite inject, so it can be used easily without import each time.
> add create prompt modal

- .gitignore
- src/MainTheme.js
- src/common/constants.js
- src/components/ChatBox/ChatBox.jsx
- src/components/SingleSelect.jsx
- src/components/Slider.jsx
- src/pages/PromptDetail/AdvancedSettings.jsx
- src/pages/PromptDetail/Common.jsx
- src/pages/PromptDetail/EditPromptDetail.jsx
- src/pages/PromptDetail/FileReaderInput.jsx
- src/pages/PromptDetail/Messages.jsx
- src/pages/PromptDetail/ModelSettings.jsx
- src/pages/PromptDetail/VariableList.jsx
- src/reducers/prompts.js
- implement advanced settings
- pass parameters to AI when chatting
> feat: advanced settings and passing parameters to AI when chatting

- src/components/ChatBox/AIAnswer.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- fix alita icon background is not transparent.
> fix: alita icon background is not transparent.

- src/components/ChatBox/ChatBox.jsx
- src/components/Slider.jsx
- src/pages/PromptDetail/AdvancedSettings.jsx
- src/pages/PromptDetail/Common.jsx
- src/pages/PromptDetail/FileReaderInput.jsx
- src/pages/PromptDetail/ModelSettings.jsx
- fix completion overflow issue
- fix slider stepper issue
- fix chat history order issue
- fix too many extra variables when inputting variables in context
- add space before the Settings icon
> fix: completion overflow issue, slider stepper issue and chat history issue

- src/api/auth.js
- src/api/prompts.js
- src/common/constants.js
- src/components/Card.jsx
- src/pages/PromptList/PromptList.jsx
change: prompts list api path
VITE_PUBLIC_PROJECT_ID in env
> fix: card onClick navigation

- src/MainTheme.js
- src/api/prompts.js
- src/components/Card.jsx
- src/components/HeaderSplitButton.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- src/components/SingleSelect.jsx
- src/components/Slider.jsx
- src/pages/PromptDetail/Common.jsx
- src/pages/PromptDetail/EditPrompt.jsx
- src/pages/PromptDetail/EditPromptTabs.jsx
- src/pages/PromptDetail/FileReaderInput.jsx
- fix bread crumbs issue
- fix select component no options issue
- fix get a prompt detail page loading icon from MUI
- fix undefined value for number input
- fix: update prompt API and tag list API
- fix: switch to edit mode when typing
- fix: hardcode context high light color
> Fix: edit prompt bugs

- src/App.jsx
- src/common/constants.js
- src/components/ChatBox/ChatBox.jsx
- src/components/SingleGroupSelect.jsx
- src/pages/PromptDetail/AdvancedSettings.jsx
- src/pages/PromptDetail/Common.jsx
- src/pages/PromptDetail/EditPromptDetail.jsx
- src/pages/PromptDetail/ModelSettings.jsx
- src/reducers/prompts.js
- new predict API
- new grouping model select
> feat: new predict API and new grouping model select

- .gitignore
- .vscode/settings.json
- src/api/prompts.js
- src/pages/PromptDetail/TagEditor.jsx
- src/pages/PromptList/Categories.jsx
- src/pages/PromptList/PromptList.jsx
- src/reducers/prompts.js
1. invoke API to fetch all prompts from backend with selected tags
2. add tags in url parameters
3. fix tag editor issue: the last character is missing
> tag related enhancements

- src/pages/PromptDetail/AdvancedSettings.jsx
- src/pages/PromptDetail/Common.jsx
- fix advance settings can't scroll issue
> fix: advance settings can't scroll

- src/pages/PromptDetail/AdvancedSettings.jsx
- src/pages/PromptDetail/Common.jsx
- fix edit page can't scroll on large screen
> fix: Edit page can't scroll on large screen

- src/common/promptApiUtils.js
- src/common/utils.jsx
- src/pages/PromptDetail/EditPrompt.jsx
- src/pages/PromptDetail/MessageInput.jsx
- src/pages/PromptDetail/hooks.jsx
- fix variable parsing is greedy
- add variable id when updating latest version
- fix DnD warnings
> fix: variable parsing is greedy; missing variable id for updating; DnD warning

- package-lock.json
- package.json
- src/pages/PromptDetail/EditModeRunTabBarItems.jsx
- src/pages/PromptDetail/VersionSelect.jsx
- vite.config.js
> fix: dot path shows 404

- src/components/StyledTabs.jsx
- src/pages/PromptDetail/Common.jsx
- fix: React does not recognize the `fullWidth` prop on a DOM
> fix: React does not recognize the `fullWidth` prop on a DOM

- src/components/Slider.jsx
- src/pages/PromptDetail/MessageInput.jsx
- src/pages/PromptList/Categories.jsx
- fix duplicated form ids
- fix passing boolean value to string pop
> Fix: dev console errors

- src/MainTheme.js
- src/components/Icons/CheckedIcon.jsx
- src/components/Icons/CircleIcon.jsx
- src/components/SingleGroupSelect.jsx
- src/components/SingleSelect.jsx
- src/components/StyledSelect.jsx
- src/pages/PromptDetail/VersionSelect.jsx
- show version status color on detail page
> feat: show version status color on detail page

- src/pages/PromptDetail/EditModeRunTabBarItems.jsx
- refresh versions when updating version fails
> fix: refresh versions when updating version fails

- src/components/NavBar.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- remove extra part of UI of My Library
> fix: remove extra part of UI of My Library

- src/components/CardList.jsx
- src/components/RightPanel.jsx
- src/components/SideBar.jsx
- src/components/StickyTabs.jsx
- src/pages/MyLibrary/MyCardList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/PromptDetail/Common.jsx
- src/pages/PromptDetail/CreateModeRunTabBarItems.jsx
- src/reducers/user.js
- support personal private project
> feat: support personal private project

- src/App.jsx
- src/common/constants.js
- src/common/utils.jsx
- src/components/Card.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/HeaderSplitButton.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- src/components/SingleSelect.jsx
- src/components/useCardList.jsx
- src/pages/MyLibrary/MyCardList.jsx
- src/pages/MyLibrary/MyCollections.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/PromptDetail/CreateModeRunTabBarItems.jsx
- src/pages/PromptDetail/EditModeRunTabBarItems.jsx
- src/pages/PromptDetail/EditPrompt.jsx
- src/pages/PromptDetail/EditPromptDetail.jsx
- src/pages/PromptDetail/VersionSelect.jsx
- src/pages/PromptDetail/hooks.jsx
- src/reducers/prompts.js
- src/routes.js
- wrong project id for edit/create prompt
> fix: wrong project id for edit/create prompt

- src/components/Card.jsx
- src/components/SingleSelect.jsx
- show prompt status color on My Library
> feat: show prompt status color on My Library

- src/components/StyledTabs.jsx
- src/pages/EditPrompt/HeaderToolBar.jsx
- src/pages/MyLibrary/MyCardList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- fix: View as public prompt should only show "my" public prompts
> fix: View as public prompt should only show "my" public prompts

- src/components/Card.jsx
- src/components/NavBar.jsx
- src/components/useCardList.jsx
- src/pages/Collcetions/CollectionDetail.jsx
- src/pages/MyLibrary/MyCardList.jsx
fix: breadcrumbs issue of collection
> fix: breadcrumbs issue of collection

- src/common/constants.js
- src/components/SingleSelect.jsx
- src/components/StickyTabs.jsx
- src/pages/MyLibrary/MyCardList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- feat: add sort by sort order
- fix: null foundOption causing error
> feat: add sort by sort order

- src/common/constants.js
- src/components/StickyTabs.jsx
fix: Sort order select is not aligned with card list
> fix: Sort order select is not aligned with card list

- src/components/RightPanel.jsx
refactor: replace right panel width with the const
> refactor: replace right panel width with the const

- src/components/Card.jsx
- src/components/StickyTabs.jsx
- src/pages/MyLibrary/MyCardList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
feat: add status filter into request
> feat: add status filter into request

- src/pages/MyLibrary/MyLibrary.jsx
fix: adjust the horizontal alignment of User information
> fix: adjust the horizontal alignment of User information

- src/pages/MyLibrary/MyCardList.jsx
fix: Datasources shows wrong data
> fix: Datasources shows wrong data

- src/App.jsx
- src/common/constants.js
- src/components/Card.jsx
- src/components/HeaderSplitButton.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- src/components/useCardList.jsx
- src/components/useCardNavigate.js
- src/pages/Collections/CollectionDetail.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/EditPrompt/CreateModeRunTabBarItems.jsx
- src/pages/EditPrompt/EditPrompt.jsx
- src/pages/EditPrompt/EditPromptTabs.jsx
- src/pages/EditPrompt/Form/TagEditor.jsx
- src/pages/EditPrompt/hooks.jsx
- src/pages/MyLibrary/MyCardList.jsx
fix: View as public/owner becomes none after some operations
> fix: View as public/owner becomes none 

- src/MainTheme.js
- src/api/prompts.js
- src/common/constants.js
- src/components/AlertDialog.jsx
- src/components/ChatBox/hooks.js
- src/pages/EditPrompt/Common.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/InputVersionDialog.jsx
- src/pages/EditPrompt/RunTab.jsx
- src/pages/EditPrompt/hooks.jsx
- src/pages/EditPrompt/useDeleteVersion.js
- src/pages/EditPrompt/usePublishVersion.js
- src/pages/EditPrompt/useSaveLatestVersion.js
- src/pages/EditPrompt/useSaveNewVersion.js
> feat:publish prompts

- src/common/constants.js
- src/common/promptApiUtils.js
- src/common/utils.jsx
- src/pages/EditPrompt/Common.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/FileReaderInput.jsx
- src/pages/EditPrompt/Form/Messages.jsx
- src/pages/EditPrompt/hooks.jsx
fix: identify variables from messages
> fix: identify variables from messages

- src/common/utils.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/StyledComponents.jsx
- fix: chat input can't expandable
- fix: chat error missing message
> fix: chat input can't expandable and chat error missing message

- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/useDeleteVersion.js
- src/pages/EditPrompt/useSaveLatestVersion.js
- src/pages/EditPrompt/useSaveNewVersion.js
- fix: bugs with save/save as version/ delete with public project id
> Fix: bugs with save/save as version/ delete with public project id

- src/pages/EditPrompt/useDeleteVersion.js
fix: delete version with wrong project id
> fix: delete version with wrong project id

- src/components/ChatBox/ChatBox.jsx
- src/pages/EditPrompt/Common.jsx
fix: alignment of expander seems a bit off
> fix: alignment of expander seems a bit off

- src/common/constants.js
fix: wrong color of rejected status
> fix: wrong color of rejected status

- src/components/SideBar.jsx
fix: make View as owner default
> fix: make View as owner default

- src/components/Card.jsx
> fix: can not view detail

- src/App.jsx
- src/common/constants.js
- src/components/Card.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- src/components/useCardNavigate.js
- src/pages/Collections/CollectionDetail.jsx
- src/pages/Collections/CreateCollection.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/EditPrompt/CreateModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/VersionSelect.jsx
- src/pages/EditPrompt/useSaveNewVersion.js
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/PromptsList.jsx
- src/pages/PromptList/Top.jsx
- src/pages/hooks.jsx
- src/routes.js
fix: wrong bread crumbs of solo urls
> fix: wrong bread crumbs of solo urls

- src/components/NavBar.jsx
fix: wrong bread crumb after creating prompt/collection
> fix: wrong bread crumb after creating prompt/collection

- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/useDeleteVersion.js
fix: wrong navigation after delete a version
> fix: wrong navigation after delete a version

- src/components/NavBar.jsx
> fix: view mode lost

- src/App.jsx
- src/components/NavBar.jsx
- src/components/SideBar.jsx
- src/components/StickyTabs.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/PromptList/Latest.jsx
> fix: show prompts latest

- src/components/Card.jsx
- src/components/NavBar.jsx
- src/components/NotificationButton.jsx
- src/components/SideBar.jsx
- src/components/StyledTabs.jsx
- src/pages/EditPrompt/EditPromptTabs.jsx
- src/pages/MyLibrary/MyLibrary.jsx
> fix: clear mocked data

- src/components/StickyTabs.jsx
- fix: My library card list misalignment
> fix: My library card list misalignment

- src/MainTheme.js
- src/api/prompts.js
- src/components/AuthorInformation.jsx
- src/components/CardList.jsx
- src/components/Categories.jsx
- src/components/Drawers/SideBar.jsx
- src/components/StickyTabs.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/PromptsList.jsx
- src/routes.js
> feat: My Libraries changes

- src/api/collections.js
- src/api/prompts.js
- src/pages/Collections/Latest.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
> feat: public collections

- src/api/prompts.js
- src/components/Drawers/SideBar.jsx
- src/components/MultipleSelect.jsx
- src/components/NavBar.jsx
- src/components/PeopleList.jsx
- src/components/StickyTabs.jsx
- src/pages/Collections/Collections.jsx
- src/pages/Collections/Latest.jsx
- src/pages/Collections/Top.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/PromptsList.jsx
- src/pages/PromptList/Latest.jsx
- src/pages/PromptList/Top.jsx
- src/slices/search.js
- src/store.js
> feat: search prompts

- src/App.jsx
- src/api/auth.js
- src/slices/user.js
> fix: avatar doesn't show

- src/pages/Collections/Latest.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/useLoadPrompts.js
fix: infinite requests when query fails
> fix: infinite requests when query fails

- src/components/AuthorInformation.jsx
- fix: make only About me scrollable
> fix: make only About me scrollable

- src/MainTheme.js
- src/common/constants.js
- src/pages/EditPrompt/Common.jsx
- src/pages/EditPrompt/CreateModeRunTabBarItems.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/InputVersionDialog.jsx
- feat: publish prompt version new UI
> feat: publish prompt version new UI

- src/MainTheme.js
- src/components/Toast.jsx
> fix: new UI of Toast

- src/pages/EditPrompt/EditPrompt.jsx
- src/pages/ModerationSpace/RequestToPublish.jsx
fix: moderation space shows wrong public prompts
> fix: moderation space shows wrong public prompts

- src/components/AuthorInformation.jsx
fix: About me supports markdown
> fix: About me supports markdown

- src/MainTheme.js
- src/api/prompts.js
- src/common/constants.js
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/useDeleteVersion.js
- src/pages/EditPrompt/useSaveLatestVersion.js
- src/pages/EditPrompt/useSaveNewVersion.js
- src/pages/EditPrompt/useUnpublishVersion.js
> feat: unpublish version

- src/components/Slider.jsx
- src/pages/EditPrompt/CreateModeRunTabBarItems.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/AdvancedSettings.jsx
- src/pages/EditPrompt/Form/ModelSettings.jsx
- src/pages/EditPrompt/RunTab.jsx
- src/slices/prompts.js
fix: discard prompt doesn't reset the UI
> fix: discard prompt doesn't reset the UI

- src/MainTheme.js
- src/components/AuthorInformation.jsx
fix: adjust the author information UI
> fix: adjust the author information UI

- src/common/constants.js
- src/components/AuthorInformation.jsx
- src/components/RightPanel.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/CommonStyles.js
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/PromptsList.jsx
- fix: make author information as close as much to the bottom of the page
> fix: make author information as close as much to the bottom of the page

- src/pages/EditPrompt/CreateModeRunTabBarItems.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
fix: save button should be disabled if nothing changes
> fix: save button should be disabled if nothing changes

- src/pages/EditPrompt/Form/FileReaderInput.jsx
- src/pages/EditPrompt/Form/Messages.jsx
- fix: drag drop support txt files
> fix: drag drop support txt files

- src/api/prompts.js
- src/components/Card.jsx
- src/components/useCardLike.js
- src/slices/prompts.js
> feat: like/unlike prompts

- src/pages/Collections/Latest.jsx
- src/pages/Collections/Top.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/useLoadPrompts.js
- src/pages/PromptList/Latest.jsx
- src/pages/PromptList/Top.jsx
- src/pages/hooks.jsx
fix: when the search changes, the page is not reset
> fix: when the search changes, the page is not reset

- src/slices/prompts.js
- fix: changes versions causes Discard button enabled.
> fix: changes versions causes Discard button enabled.

- src/api/collections.js
- src/api/prompts.js
- src/pages/Collections/Collections.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/hooks.jsx
fix: the badge count of total items changes with the query result
> fix: the badge count of total items changes with the query result

- src/components/ChatBox/AIAnswer.jsx
- fix: chat box ui issue with table
> fix: chat box ui issue with table

- src/pages/EditPrompt/Form/TagEditor.jsx
- src/pages/hooks.jsx
- fix: disable tag editor for non-owner view mode
> fix: disable tag editor for non-owner view mode

- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- fix: My Libraries collection tab supports filtering by status
> fix: My Libraries collection tab supports filtering by status

- src/common/constants.js
- src/components/MultipleSelect.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- fix: my collections filter by status
> fix: my collections filter by status

- src/App.jsx
> fix: remove extra basename

- src/App.jsx
> fix: restore basename

- src/App.jsx
> fix: eye fail to load

- src/api/prompts.js
- src/components/NavBar.jsx
- src/pages/Collections/Collections.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/hooks.jsx
- fix: tab badge count should changes according to query
> fix: tab badge count should changes according to query

- src/components/NavBar.jsx
- fix: the search key word should be at least 3 letters long
> fix: the search key word should be at least 3 letters long

- src/common/constants.js
> fix: undefined variable

- src/pages/Collections/Latest.jsx
- src/pages/Collections/Top.jsx
- src/pages/MyLibrary/useQueryTrendingAuthor.js
- src/pages/PromptList/Latest.jsx
- src/pages/PromptList/Top.jsx
- fix: Trending authors UI should be close to the bottom of the page
> fix: Trending authors UI should be close to the bottom of the page

- src/components/AuthorInformation.jsx
- src/components/StatusDot.jsx
- src/pages/Collections/Latest.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/PromptsList.jsx
- fix: the tab badge count doesn't change when tags selected
> fix: the tab badge count doesn't change when tags selected

- src/api/prompts.js
- src/slices/prompts.js
> fix: tag list API change

- src/pages/Collections/Collections.jsx
- fix: collection list api support searching by tags
> fix: collection list api support searching by tags

- src/components/NavBar.jsx
- src/pages/Collections/Latest.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- fix: collections page doesn't show loading when selecting tags
> fix: collections page doesn't show loading when selecting tags

- src/App.jsx
- src/common/constants.js
- src/components/NavBar.jsx
- src/components/useCardLike.js
- src/components/useCardNavigate.js
- src/pages/Collections/CollectionDetail.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/hooks.jsx
- fix: breadcrumbs for collections and collection prompt details
> fix: breadcrumbs for collections and collection prompt details

- src/api/prompts.js
- src/components/Categories.jsx
- src/pages/hooks.jsx
- fix: user profile page, tag list should not show those without prompt
> fix: user profile page, tag list should not show those without prompt

- src/common/constants.js
- src/pages/Collections/Collections.jsx
- src/pages/Collections/Latest.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/PromptList/Latest.jsx
- fix: collection statuses filtering
> fix: collection statuses filtering

- src/components/Card.jsx
- fix: like star display issue
> fix: like star display issue

- src/api/collections.js
- src/components/Card.jsx
- src/components/useCardLike.js
- feat: like public collections
> feat: like public collections

- src/components/Card.jsx
- src/components/useCardLike.js
- src/components/useCardList.jsx
- fix: liking collection doesn't update UI
> fix: liking collection doesn't update UI

- src/components/AuthorInformation.jsx
- fix: user profile API "Owned Items", "Shared Items", "Reward" update
> fix: user profile API "Owned Items", "Shared Items", "Reward" update

- src/api/prompts.js
- src/pages/Discover/Prompts.jsx
- src/pages/PromptList/MyLiked.jsx
- feat: My liked tab of prompts
> feat: My liked tab of prompts

- src/components/Categories.jsx
- src/pages/PromptList/MyLiked.jsx
- fix: filter my liked tags for prompts My liked tab.
> fix: filter my liked tags for prompts My liked tab.

- src/api/prompts.js
- src/common/constants.js
- src/components/Drawers/SideBar.jsx
- src/pages/Collections/Collections.jsx
- src/pages/Discover/Prompts.jsx
- src/pages/PromptList/Trending.jsx
> feat: trending prompts

- src/components/Card.jsx
- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/EditModeToolBar.jsx
- fix: my libraries collection prompt mixed data
> fix: my libraries collection prompt mixed data

- src/api/collections.js
- src/components/AuthorInformation.jsx
- src/components/Card.jsx
- src/components/useCardLike.js
- src/components/useCardList.jsx
- src/pages/Collections/Trending.jsx
- fix: hide likes of my libraries; update badges
> fix: hide likes of my libraries; update badges

- src/App.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/UserProfile.jsx
we do not show not published items
> Fixing public view of user's library

- src/components/Drawers/SideBar.jsx
- src/components/Drawers/common.jsx
- src/components/HeaderSplitButton.jsx
- src/components/TooltipForDisablePersonalSpace.jsx
- fix: disable buttons +prompt and my library
> fix: disable buttons +prompt and my library

- package.json
- src/App.jsx
- src/api/social.js
- src/components/FeedbackDialog.jsx
- src/components/StyledDialog.jsx
> adding feedback function button on every page

- src/components/FeedbackDialog.jsx
- fix: remove extra content and fix devTool error
> fix: remove extra content and fix devTool error

- src/pages/EditPrompt/Form/AdvancedSettings.jsx
- src/pages/EditPrompt/Form/ModelSettings.jsx
- fix: advanced settings fixes
> fix: advanced settings fixes

- src/pages/EditPrompt/Form/AdvancedSettings.jsx
- src/pages/EditPrompt/RunTab.jsx
- fix: advanced settings max token input forces default value
> fix: advanced settings max token input forces default value

- src/common/constants.js
- src/common/promptApiUtils.js
- src/components/SingleGroupSelect.jsx
- src/pages/EditPrompt/Form/AdvancedSettings.jsx
- src/pages/EditPrompt/Form/ModelSettings.jsx
- src/pages/EditPrompt/RunTab.jsx
fix: save selected integration name
> fix: save selected integration name

- src/pages/MyLibrary/MyLibrary.jsx
- fix: the default status of my libraries should be all
> fix: the default status of my libraries should be all

- src/App.jsx
- src/components/NavBar.jsx
- src/components/useCardNavigate.js
- fix: prompts/collections default tab issue, it should be latest
> fix: prompts/collections default tab issue, it should be latest

- src/components/AuthorInformation.jsx
- fix: user profile newline issue
> fix: user profile newline issue

- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
> fix: chat dialog actions

- src/components/useCardLike.js
- fix: unlike collection latest causing it disappearing.
> fix: unlike collection latest causing it disappearing.

- src/App.jsx
- src/components/FeedbackDialog.jsx
- src/components/NavBar.jsx
- src/components/useCardNavigate.js
- src/pages/EditPrompt/Form/VersionSelect.jsx
- src/pages/EditPrompt/ModeratorRunTabBarItems.jsx
- src/pages/EditPrompt/useDeleteVersion.js
- src/pages/EditPrompt/useSaveNewVersion.js
- fix: special characters causing navigation issue.
> fix: special characters causing navigation issue.

- src/components/useCardLike.js
- src/pages/Collections/CollectionDetail.jsx
- src/slices/prompts.js
fix: collection detail API changes causes crash
> fix: collection detail API changes causes crash

- src/slices/prompts.js
- fix: my library collection detail page displaying tag issue
> fix: my library collection detail page displaying tag issue

- src/components/NavBar.jsx
- fix: bread crumb is wrong for details page opened from search result
> fix: bread crumb is wrong for details page opened from search result

- src/components/AuthorInformation.jsx
- fix: show more instead of read more
> fix: show more instead of read more

- src/pages/Collections/CollectionDetail.jsx
- fix: export collection tooltip issue
> fix: export collection tooltip issue

- src/pages/Settings/CreateDeployment.jsx
- fix: wrong query with undefined project id
> fix: wrong query with undefined project id

- src/api/integrations.js
- src/pages/Settings/Configuration.jsx
- src/pages/Settings/CreateDeployment.jsx
- src/pages/Settings/components/DeploymentActions.jsx
> fix: settings bugs

- src/MainTheme.js
- src/components/Icons/EllipseIcon.jsx
- src/pages/Settings/components/DeploymentActions.jsx
- src/pages/Settings/components/DeploymentsTable.jsx
> fix: inherited integration

- src/components/SingleGroupSelect.jsx
- src/pages/EditPrompt/RunTab.jsx
- fix: select max height and mode selection ui
> fix: select max height and mode selection ui

- src/components/SingleGroupSelect.jsx
> fix: crash issue

- src/components/StickyTabs.jsx
- fix: card list alignment issue
> fix: card list alignment issue

- src/pages/ModerationSpace/ModerationSpace.jsx
- fix: moderation space alignment
> fix: moderation space alignment

- src/components/SecretToggle.jsx
- src/pages/Settings/CreateDeployment.jsx
> fix: settings issues

- src/pages/Settings/components/DeploymentsTable.jsx
- fix: deployment page fix height issue
> fix: deployment page fix height issue

- src/components/SingleGroupSelect.jsx
- fix: empty models causing crash
> fix: empty models causing crash

- src/pages/EditPrompt/RunTab.jsx
- fix: remove filtering of models
> fix: remove filtering of models

- src/api/auth.js
- fix: refresh token list after creating/deleting a token
> fix: refresh token list after creating/deleting a token

- src/components/AuthorInformation.jsx
- fix: about me shows table wrong
> fix: about me shows table wrong

- src/common/constants.js
- src/pages/EditPrompt/Form/AdvancedSettings.jsx
- src/pages/EditPrompt/RunTab.jsx
- fix: change position of Advanced settings for tablet view.
> fix: change position of Advanced settings for tablet view.

- src/pages/EditPrompt/EditModeRunTabBarItems.jsx
- src/pages/EditPrompt/Form/InputVersionDialog.jsx
- fix: Add "Publish version" modal to publish saved version.
> fix: Add "Publish version" modal to publish saved version.

- src/common/constants.js
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/ChatInput.jsx
- src/components/ChatBox/StyledComponents.jsx
- src/components/ChatBox/UserMessage.jsx
- src/components/ChatBox/hooks.js
- src/components/GroupedButton.jsx
- src/pages/DataSources/Components/BuildTabCotent.jsx
- src/pages/DataSources/Components/ChatForm.jsx
- src/pages/DataSources/Components/ChatSettings.jsx
- src/pages/DataSources/Components/GenerateFile.jsx
- src/pages/EditPrompt/Form/InputVersionDialog.jsx
- src/pages/MyLibrary/ProjectSelect.jsx
- src/slices/prompts.js
- feat: data sources chat component
> feat: data sources chat component

- src/App.jsx
- src/api/auth.js
- src/api/datasources.js
- src/components/BasicAccordion.jsx
- src/components/StyledInputEnhancer.jsx
- src/pages/DataSources/Components/BuildTabCotent.jsx
- src/pages/DataSources/Components/DataSet.jsx
- src/pages/DataSources/Components/DataSets.jsx
- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/DataSources/Components/Source.jsx
- src/pages/DataSources/Components/Sources/SourceFile.jsx
- src/pages/DataSources/Components/Sources/SourceGit.jsx
- src/pages/DataSources/Components/Summarization.jsx
- src/pages/DataSources/Components/Transformers.jsx
- src/pages/DataSources/CreateDatasource.jsx
- src/pages/DataSources/EditDatasource.jsx
- src/routes.js
I have habdled adding datasources to project
Create datasource page, datasource detail page, dataset add dialog
It is still WIP, needs to be discussed
For Monday, let's focus on my library datasource list page
> adding datasources

- src/api/datasources.js
- src/components/Card.jsx
- src/components/useCardLike.js
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- feat: my library data sources
> feat: my library data sources

- src/api/datasources.js
- src/components/DataTable.jsx
- src/components/HeaderSplitButton.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/MyLibrary/useLoadDatasources.js
- src/pages/MyLibrary/useLoadPrompts.js
- src/pages/hooks.jsx
- src/routes.js
- feat: data source on All tab of My Library
> feat: data source on All tab of My Library

- src/components/HeaderSplitButton.jsx
- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- fix: show create datasources
- fix: use mocked storages
> fix: show create datasources

- src/pages/DataSources/Components/DatasourceCreateForm.jsx
fix: add tag list for creating data sources
> fix: add tag list for creating data sources

- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: show storage name on detail page
> fix: show storage name on detail page

- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: correct the model settings of creating datasource
> fix: correct the model settings of creating datasource

- src/api/datasources.js
- src/components/DataRowAction.jsx
- src/components/DataTable.jsx
- fix: wrong icon of data sources and actions in table view
> fix: wrong icon of data sources and actions in table view

- src/api/datasources.js
- src/common/constants.js
- src/pages/DataSources/Components/DataSet.jsx
- src/pages/DataSources/Components/DataSets.jsx
- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/DataSources/Components/Source.jsx
- src/pages/DataSources/Components/Sources/SourceGit.jsx
- src/pages/DataSources/Components/Summarization.jsx
- src/pages/DataSources/Components/Transformers.jsx
- src/pages/DataSources/EditDatasource.jsx
- src/pages/DataSources/constants.js
> fixing data structures

- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/StyledComponents.jsx
- src/pages/DataSources/Components/ChatForm.jsx
- src/pages/DataSources/CreateDatasource.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: adjust ui of create data source and data source details
> fix: adjust ui of create data source and data source details

- src/components/SingleGroupSelect.jsx
- src/pages/DataSources/Components/AdvanceChatSettings.jsx
- src/pages/DataSources/Components/ChatForm.jsx
- src/pages/DataSources/Components/ChatSettings.jsx
- src/pages/DataSources/Components/DatasourceCreateForm.jsx
- src/pages/DataSources/Components/DuplicateSettings.jsx
- src/pages/DataSources/Components/ModelCompatibleIcon.jsx
- src/pages/DataSources/Components/SearchSettings.jsx
- src/pages/DataSources/Components/useModelOptions.js
- src/pages/DataSources/EditDatasource.jsx
- src/pages/EditPrompt/RunTab.jsx
- src/pages/hooks.jsx
- feat: UI of chat box of datasource
> feat: UI of chat box of data source

- src/components/SingleGroupSelect.jsx
- src/components/StyledTabs.jsx
- src/pages/DataSources/Components/ChatForm.jsx
- src/pages/DataSources/Components/DataSourceView.jsx
- src/pages/DataSources/Components/DatasourceEditForm.jsx
- src/pages/DataSources/Components/DiscardButton.jsx
- src/pages/DataSources/Components/EditDataSourceTabBar.jsx
- src/pages/DataSources/Components/dataSourceVlidateSchema.js
- src/pages/DataSources/EditDatasource.jsx
> feat: edit data source UI

- src/pages/DataSources/Components/ChatForm.jsx
> fix: chat state is empty

- src/common/constants.js
- src/components/AuthorInformation.jsx
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/UserMessage.jsx
- src/components/Markdown.jsx
- src/pages/DataSources/Components/ChatPanel.jsx
- src/pages/DataSources/Components/DataSets.jsx
- src/pages/DataSources/Components/DuplicatePanel.jsx
- src/pages/DataSources/Components/SearchPanel.jsx
- src/pages/Settings/Profile.jsx
- fix: data source chat issues
> fix: data source chat issues

- src/pages/DataSources/Components/DatasourceOperationPanel.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: the misalignment of chat panel when showing AdvanceSettings.
> fix: the misalignment of chat panel when showing AdvanceSettings.

- src/pages/DataSources/Components/DatasourceOperationPanel.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: hide chat advance settings
- fix: hide data source edit button
- fix: hide save/discard buttons
> fix: hide chat advance settings

- src/pages/DataSources/Components/DataSourceView.jsx
- src/pages/DataSources/Components/DatasourceEditForm.jsx
- src/pages/DataSources/Components/EmbeddingModelStorageView.jsx
- fix: disable editing embedding model and storage
> fix: disable editing embedding model and storage

- src/pages/Settings/CreateDeployment.jsx
- src/pages/Settings/Deployments.jsx
- src/pages/Settings/components/AddDeploymentButton.jsx
- src/pages/Settings/components/DeploymentsCardList.jsx
- src/pages/Settings/components/DeploymentsTable.jsx
- feat: create hugging face deployment
> feat: create hugging face deployment

- src/pages/Settings/CreateDeployment.jsx
- fix: make the api token of hugging face optional
> fix: make the api token of hugging face optional

- src/pages/Settings/CreateDeployment.jsx
> fix: show required

- src/pages/DataSources/Components/Source.jsx
- src/pages/DataSources/Components/Sources/SourceFile.jsx
> feat: file source ui

- src/api/datasources.js
- src/common/constants.js
- src/components/SingleGroupSelect.jsx
- src/pages/DataSources/Components/AdvanceChatSettings.jsx
- src/pages/DataSources/Components/ChatPanel.jsx
- src/pages/DataSources/Components/DataSourceView.jsx
- src/pages/DataSources/Components/DatasourceEditForm.jsx
- src/pages/DataSources/Components/DatasourceOperationPanel.jsx
- src/pages/DataSources/Components/DeduplicatePanel.jsx
- src/pages/DataSources/Components/DeduplicateSettings.jsx
- src/pages/DataSources/Components/EditDataSourceTabBar.jsx
- src/pages/DataSources/Components/SearchPanel.jsx
- src/pages/DataSources/Components/SearchSettings.jsx
- src/pages/DataSources/EditDatasource.jsx
> feat: update datasource

- src/api/datasources.js
- src/common/utils.jsx
- src/components/FileUploadControl.jsx
- src/pages/DataSources/Components/DataSet.jsx
- src/pages/DataSources/Components/Sources/SourceFile.jsx
> feat: file source type

- src/pages/DataSources/Components/Sources/SourceGit.jsx
- fix: password & username or ssh_key
> fix: password & username or ssh_key

- src/pages/DataSources/Components/DataSet.jsx
- src/pages/DataSources/Components/DataSets.jsx
- src/pages/DataSources/EditDatasource.jsx
> fix: can't update dataset

- src/pages/EditPrompt/Form/ModelSettings.jsx
- fix: settings icon background color issue
> fix: settings icon background color issue

- src/api/integrations.js
- src/common/constants.js
- src/components/Icons/AzureIcon.jsx
- src/pages/Settings/CreateDeployment.jsx
- src/pages/Settings/components/AddDeploymentButton.jsx
- feat: available integrations
> feat: available integrations

- src/pages/DataSources/Components/Datasources/DatasourceEditForm.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: update datasource payload
> fix: update datasource payload

- src/api/datasources.js
- src/common/constants.js
- src/components/Drawers/SideBar.jsx
- src/pages/DataSources/DataSources.jsx
- src/pages/DataSources/Latest.jsx
- src/pages/DataSources/MyLiked.jsx
- src/pages/DataSources/Trending.jsx
> feat: public datasources

- src/pages/DataSources/EditDatasource.jsx
- src/pages/DataSources/constants.js
- src/pages/DataSources/useHasDataSourceChanged.js
- fix: show blocker only when the user is editing something.
> fix: show blocker only when the user is editing something.

- src/MainTheme.js
- src/components/DataTable.jsx
- src/components/DataTableRow.jsx
- src/components/StyledInputEnhancer.jsx
- src/pages/Prompts/Components/Common.jsx
- src/pages/Settings/CreateDeployment.jsx
- src/pages/Settings/Settings.jsx
- src/pages/Settings/components/AddModelForm.jsx
- src/pages/Settings/components/DeploymentsCardList.jsx
- src/pages/Settings/components/DeploymentsTable.jsx
- src/pages/Settings/components/ModelsTable.jsx
- src/pages/Settings/components/PersonalTokenTable.jsx
- src/pages/Settings/components/ProjectTokenTable.jsx
- fix: table border color issue
> fix: table border color issue

- src/pages/DataSources/Components/Datasources/EditDataSourceTabBar.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: disable save/discard buttons after updating datasource
> fix: disable save/discard buttons after updating datasource

- src/components/ChatBox/ChatInput.jsx
- src/pages/DataSources/Components/Datasources/SearchPanel.jsx
- src/pages/Prompts/Components/RunTab.jsx
adding cleanup argument for chat input window
> fixing prompt chat options

- src/pages/Prompts/Components/RunTab.jsx
> fix: create prompt crash

- src/components/Like.jsx
- src/components/useCardLike.js
- feat: disable like datasource
> feat: disable like datasource

- src/api/datasources.js
- src/components/Like.jsx
- src/components/useCardLike.js
- src/pages/DataSources/Components/Datasources/DataSourceDetailToolbar.jsx
- src/pages/DataSources/EditDatasource.jsx
- src/pages/DataSources/useDatasourceDispatchQueryParams.js
- src/pages/Prompts/Components/EditModeToolBar.jsx
- feat: like/unlike datasource
> feat: like/unlike datasource

- src/pages/DataSources/EditDatasource.jsx
- fix: enable save button when anything changes
> fix: enable save button when anything changes

- src/pages/Collections/CollectionForm.jsx
- src/pages/DataSources/Components/Datasources/DatasourceCreateForm.jsx
- src/pages/MyLibrary/ProjectSelect.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: creating collection with multiple projects
> fix: creating collection with multiple projects

- src/pages/DataSources/Components/Datasources/AdvancedSearchSettings.jsx
> fix: string content label

- src/common/constants.js
- src/components/ChatBox/AIAnswer.jsx
- fix: markdown links readable issue
> fix: markdown links readable issue

- src/pages/DataSources/Components/Datasources/DataSourceView.jsx
- src/pages/DataSources/Components/Datasources/DatasourceContext.jsx
- src/pages/DataSources/Components/Datasources/DatasourceCreateForm.jsx
- src/pages/DataSources/Components/Datasources/DatasourceEditForm.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: datasource should support multiline
> fix: datasource context should support multiline

- src/components/SingleSelect.jsx
- src/pages/Collections/CollectionForm.jsx
- src/pages/DataSources/Components/Datasources/DatasourceCreateForm.jsx
- src/pages/DataSources/Components/Datasources/DatasourceEditForm.jsx
- src/pages/MyLibrary/ProjectSelect.jsx
- src/pages/Prompts/Components/RunTab.jsx
> fix: project select ui

- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/DataSources/Components/Datasources/DatasourceOperationPanel.jsx
- src/pages/DataSources/Components/Datasources/DeduplicatePanel.jsx
- src/pages/DataSources/Components/Datasources/SearchPanel.jsx
- src/pages/DataSources/EditDatasource.jsx
> fix: keep chat result

- src/components/NameDescriptionReadOnlyView.jsx
- src/pages/DataSources/Components/Datasources/DataSourceView.jsx
- src/pages/Prompts/Components/RunTab.jsx
- src/slices/prompts.js
- fix: UI change, Tags displaying in General block
> fix: UI change, Tags displaying in General block

- src/api/datasources.js
- src/pages/DataSources/EditDatasource.jsx
- fix: wrong datasource id for saving; wrong unpublish method
> fix: wrong datasource id for saving; wrong unpublish method

- src/pages/DataSources/Components/Datasources/EmbeddingModelStorageView.jsx
- fix: Correct the font of items on Datasource  page in General block
> fix: Correct the font of items on Datasource  page in General block

- src/components/DataRowAction.jsx
- src/pages/Collections/CollectionDetail.jsx
- src/pages/Collections/useCollectionActions.jsx
- src/pages/Prompts/Components/ExportDropdownMenu.jsx
- fix: fail to export prompts/collections
> fix: fail to export prompts/collections

- src/api/datasources.js
- src/pages/DataSources/Components/Datasources/EditDataSourceTabBar.jsx
- src/pages/DataSources/EditDatasource.jsx
- fix: the datasource detail is not refreshed after editing
> fix: the datasource detail is not refreshed after editing

- src/components/BasicAccordion.jsx
- src/components/StyledTabs.jsx
- fix: set background for accordion and tab  panel
> fix: set background for accordion and tab  panel

- src/pages/Prompts/Components/EditModeRunTabBarItems.jsx
- src/pages/Prompts/Components/Form/InputVersionDialog.jsx
- fix: UI/UX issue: Add "Publish version" modal to publish saved version.
> fix: UI/UX issue: Add "Publish version" modal to publish saved version.

- src/components/Card.jsx
- fix: the navigation clickable area of card is too small
> fix: the navigation clickable area of card is too small

- src/pages/Prompts/Components/ExportDropdownMenu.jsx
- fix: exporting uses wrong project id
> fix: exporting uses wrong project id

- src/components/Slider.jsx
- fix: slider input precision issue.
> fix: slider input precision issue.

- src/common/utils.jsx
- src/pages/DataSources/Components/Datasources/DatasourceCreateForm.jsx
- fix: truncate long 404 error message
> fix: truncate long 404 error message

- src/pages/DataSources/Components/Datasources/DataSourceDetailToolbar.jsx
- fix: show author avatar of non private datasource
> fix: show author avatar of non private datasource

- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/hooks/useSocket.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- feat: steaming datasource chat
> feat: steaming datasource chat

- src/api/datasources.js
- src/common/constants.js
- src/components/Toast.jsx
- src/components/useToast.jsx
- src/pages/DataSources/Components/Datasets/DataSet.jsx
- src/pages/DataSources/Components/Datasets/DataSetActions.jsx
- src/pages/DataSources/Components/Datasets/DataSets.jsx
- src/pages/DataSources/Components/Datasets/StatusIcon.jsx
- src/pages/DataSources/EditDatasource.jsx
- src/pages/DataSources/constants.js
- fix: dataset status streaming
> fix: dataset status streaming

- src/pages/Prompts/Components/AddToCollectionDialog.jsx
- src/pages/Prompts/Components/Form/ProjectCollectionFilter.jsx
- fix: UI issue, correct "Add to collections" modal
> fix: UI issue, correct "Add to collections" modal

- src/components/SingleGroupSelect.jsx
- fix: UI issue - correct dropdown component (padding, color)
> fix: UI issue - correct dropdown component (padding, color)

- src/pages/DataSources/EditDatasource.jsx
- src/pages/Prompts/Components/Form/Messages.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: UI issue - correct paddings between accordion items (+font)
> fix: UI issue - correct paddings between accordion items (+font)

- src/components/GroupedButton.jsx
- fix: group buttons hover style
> fix: group buttons hover style

- src/pages/DataSources/Components/Datasets/Transformers.jsx
- src/pages/DataSources/Components/Sources/Source.jsx
- src/pages/Prompts/Components/Common.jsx
- fix: UI issue - text fields on Datasource page in dataset form
> fix: UI issue - text fields on Datasource page in dataset form

- src/hooks/useSocket.jsx
- fix: access null socket instance issue
> fix: access null socket instance issue

- src/pages/DataSources/Components/Datasets/DataSet.jsx
- fix: show dataset creation messages
> fix: show dataset creation messages

- src/pages/Prompts/Components/validatePrompt.js
- fix: highlight prompt variable syntax error
> fix: highlight prompt variable syntax error

- src/components/ChatBox/ChatBox.jsx
- fix: add loading states to chat and completion
> fix: add loading states to chat and completion

- src/api/prompts.js
- src/common/constants.js
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/UserMessage.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
> refactor: chat completion

- src/common/constants.js
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
> fix: socket error handling

- src/components/AnimatedProgress.jsx
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/DataSources/Components/Datasources/DeduplicatePanel.jsx
- src/pages/DataSources/Components/Datasources/SearchPanel.jsx
- fix: chat in progress status
> fix: chat in progress status

- src/common/promptApiUtils.js
- src/common/utils.jsx
- src/pages/DataSources/Components/Datasources/AdvancedChatSettings.jsx
- src/pages/DataSources/Components/Datasources/AdvancedSearchSettings.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/DataSources/Components/Datasources/ChatSettings.jsx
- src/pages/DataSources/Components/Datasources/DatasourceOperationPanel.jsx
- src/pages/DataSources/Components/Datasources/DeduplicatePanel.jsx
- src/pages/DataSources/Components/Datasources/DeduplicateSettings.jsx
- src/pages/DataSources/Components/Datasources/EditDataSourceTabBar.jsx
- src/pages/DataSources/Components/Datasources/SearchPanel.jsx
- src/pages/DataSources/Components/Datasources/SearchSettings.jsx
- src/pages/DataSources/Components/Datasources/useSaveVersion.js
- src/pages/DataSources/EditDatasource.jsx
- src/pages/DataSources/constants.js
- src/pages/DataSources/useHasDataSourceChanged.js
- fix: adapt datasources settings to new format
> fix: adapt datasources settings to new format

- src/components/DataRowAction.jsx
- src/pages/DataSources/Components/Datasources/DataSourceDetailToolbar.jsx
- src/pages/DataSources/EditDatasource.jsx
- src/pages/Prompts/Components/AddToCollectionDialog.jsx
- src/pages/Prompts/Components/EditModeToolBar.jsx
- fix: add collection button for public datasource
> fix: add collection button for public datasource

- src/components/ChatBox/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
> fix: socket sub/unsub bug

- src/components/NameDescriptionReadOnlyView.jsx
- src/pages/Applications/Components/Applications/ApplicationView.jsx
- src/pages/DataSources/Components/Datasources/DataSourceView.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: show ids of prompt, datasource and application
> fix: show ids of prompt, datasource and application

- src/pages/DataSources/Components/Datasources/AdvancedChatSettings.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/DataSources/Components/Datasources/DatasourceOperationPanel.jsx
- fix: maximum_length cannot be edited
> fix: maximum_length cannot be edited

- src/pages/DataSources/Components/Datasources/AdvancedChatSettings.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/DataSources/Components/Datasources/DataSourceDetailToolbar.jsx
- src/pages/DataSources/Components/Datasources/DatasourceOperationPanel.jsx
- fix: update advanced settings for chat
> fix: update advanced settings for chat

- src/components/ChatBox/ChatInput.jsx
- src/components/ChatBox/UserMessage.jsx
- fix: disable markdown for User Message
> fix: disable markdown for User Message

- src/api/datasources.js
- src/components/FileUploadControl.jsx
- src/hooks/useSocket.jsx
- src/pages/DataSources/Components/Datasets/DataSet.jsx
- src/pages/DataSources/Components/Datasets/DataSetActions.jsx
- src/pages/DataSources/Components/Datasets/StatusIcon.jsx
> fix: dataset status buttons

- src/App.jsx
- fix: disable API requests when the application is configured wrongly.
> fix: disable API requests when the application is configured wrongly.

- src/pages/ModerationSpace/ModerationSpace.jsx
- src/routes.js
- fix: moderation space card navigation issue
> fix: moderation space card navigation issue

- src/components/HeaderSplitButton.jsx
- src/components/ModelSelectDialog.jsx
- src/components/useBreadCrumbs.js
- fix: allow selecting model for imported prompts
> fix: allow selecting model for imported prompts

- src/pages/DataSources/Components/Datasources/DataSourceView.jsx
- fix: correct datasource id label
> fix: correct datasource id label

- src/pages/Prompts/Components/Form/MessageInput.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: set model for public prompt if the original model is unavailable.
> fix: set model for public prompt if the original model is unavailable.

- src/common/promptApiUtils.js
- src/components/ChatBox/ChatBox.jsx
- src/pages/Applications/Components/Applications/ApplicationContext.jsx
- src/pages/Applications/Components/Applications/ApplicationCreateForm.jsx
- src/pages/Applications/Components/Applications/ApplicationCreationValidateSchema.js
- src/pages/Applications/Components/Applications/ApplicationRightContent.jsx
- src/pages/Applications/Components/Applications/CreateApplicationTabBar.jsx
- src/pages/Applications/Components/Applications/DiscardButton.jsx
- src/pages/Applications/Components/Applications/useCreateApplication.jsx
- src/pages/Applications/Components/Tools/ApplicationTools.jsx
- src/pages/Applications/CreateApplication.jsx
- src/pages/Applications/EditApplication.jsx
- src/pages/Applications/useApplicationInitialValues.jsx
- src/pages/Prompts/Components/Form/ModelSettings.jsx
- src/pages/Prompts/Components/RunTab.jsx
> feat: create application

- src/common/promptApiUtils.js
- src/pages/Applications/constants.js
- src/pages/DataSources/Components/Datasources/DatasourceCreateForm.jsx
- src/pages/Prompts/Components/Form/AdvancedSettings.jsx
- src/pages/Prompts/Components/Form/ModelSettings.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: rename name of model to model_name
> fix: rename name of model to model_name

- src/common/promptApiUtils.js
- src/components/ChatBox/ChatBox.jsx
- fix: make prompts compatible with the old model name
> fix: make prompts compatible with the old model name

- src/components/HeaderSplitButton.jsx
- fix: set default model for importing prompts
> fix: set default model for importing prompts

- src/api/secrets.js
- src/common/constants.js
- src/components/Toggle.jsx
- src/pages/Applications/Components/Tools/APIKeyFrom.jsx
- src/pages/Applications/Components/Tools/AuthenticationSelect.jsx
- src/pages/Applications/Components/Tools/OAuthFrom.jsx
feat: authentication of Open API tool
> feat: authentication of Open API tool

- src/components/ChatBox/ActionButtons.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/hooks.js
FIx issues: 
1. regenerating 2 prompt chat response will get the same response
2. stop generation button is shown for non-streaming AIAnswer
> Fix/regenerating mix+stop generating button issue

- src/pages/Applications/Components/Tools/CustomInput.jsx
- src/pages/Applications/Components/Tools/ToolCard.jsx
- src/pages/Applications/Components/Tools/ToolCustom.jsx
- src/pages/Applications/Components/Tools/ToolDatasource.jsx
- src/pages/Applications/Components/Tools/ToolForm.jsx
- src/pages/Applications/Components/Tools/ToolFormBackButton.jsx
- src/pages/Applications/Components/Tools/ToolOpenAPI.jsx
- src/pages/Applications/Components/Tools/consts.js
- feat: application custom tool
> feat: application custom tool

- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ChatInput.jsx
- fix: the reference temporarily hides the answer action buttons
> fix: the reference temporarily hides the answer action buttons

- src/pages/Applications/Components/Tools/OpenAPIActionsTable.jsx
- src/pages/DataSources/Components/Sources/SourceConfluence.jsx
- fix: decrease default values for confluence datasource make it 10 / 100 instead of 50 / 1000
> fix: decrease default values for confluence datasource

- src/pages/Applications/Components/Tools/ToolCustom.jsx
- src/pages/Applications/Components/Tools/ToolOpenAPI.jsx
- src/pages/Applications/Components/Tools/consts.js
- fix: display functions of Custom tool
> fix: display functions of Custom tool

- src/pages/Prompts/Components/AddToCollectionDialog.jsx
- src/pages/Prompts/Components/Form/ProjectCollectionFilter.jsx
- fix: hide project selection dropdown in collection dialog
> fix: hide project selection dropdown in collection dialog

- src/pages/Applications/Components/Tools/ToolCard.jsx
- fix: show functions of application custom tool
> fix: show functions of application custom tool

- src/components/DataTableHead.jsx
- src/pages/Applications/Latest.jsx
- src/pages/Applications/MyLiked.jsx
- src/pages/Applications/Trending.jsx
- src/pages/Collections/Latest.jsx
- src/pages/Collections/MyLiked.jsx
- src/pages/Collections/Trending.jsx
- src/pages/DataSources/Latest.jsx
- src/pages/DataSources/MyLiked.jsx
- src/pages/DataSources/Trending.jsx
- src/pages/ModerationSpace/AllStuffList.jsx
- src/pages/ModerationSpace/ModerationCollectionList.jsx
- src/pages/ModerationSpace/ModerationPromptList.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/MyLibrary.jsx
- src/pages/Prompts/Latest.jsx
- src/pages/Prompts/MyLiked.jsx
- src/pages/Prompts/Top.jsx
- src/pages/Prompts/Trending.jsx
- src/pages/hooks.jsx
- fix: table sorting does not update table
> fix: table sorting does not update table

- src/pages/Applications/Components/Applications/ApplicationRightContent.jsx
- src/pages/Applications/CreateApplication.jsx
- src/pages/Prompts/Components/RunTab.jsx
- fix: application create screen scroll
> fix: application create screen scroll

- src/components/Card.jsx
fix: remove icon from application card
> fix: remove icon from application card

- src/api/applications.js
- src/common/constants.js
- src/common/utils.jsx
- src/components/SingleSelectWithSearch.jsx
- src/pages/Applications/Components/Applications/ApplicationContext.jsx
- src/pages/Applications/Components/Applications/ApplicationRightContent.jsx
- src/pages/Applications/Components/Applications/ApplicationView.jsx
- src/pages/Applications/Components/Applications/ConversationStarters.jsx
- src/pages/Applications/Components/Applications/CreateApplicationTabBar.jsx
- src/pages/Applications/Components/Applications/EditApplicationTabBar.jsx
- src/pages/Applications/Components/Applications/useCreateApplication.jsx
- src/pages/Applications/Components/Applications/useSaveVersion.js
- src/pages/Applications/Components/Tools/APIKeyFrom.jsx
- src/pages/Applications/Components/Tools/ApplicationTools.jsx
- src/pages/Applications/Components/Tools/AuthenticationSelect.jsx
- src/pages/Applications/Components/Tools/DatasourceSelect.jsx
- src/pages/Applications/Components/Tools/OAuthFrom.jsx
- src/pages/Applications/Components/Tools/PromptSelect.jsx
- src/pages/Applications/Components/Tools/ToolCard.jsx
- src/pages/Applications/Components/Tools/ToolCustom.jsx
- src/pages/Applications/Components/Tools/ToolDatasource.jsx
- src/pages/Applications/Components/Tools/ToolForm.jsx
- src/pages/Applications/Components/Tools/ToolOpenAPI.jsx
- src/pages/Applications/Components/Tools/ToolPrompt.jsx
- src/pages/Applications/Components/Tools/consts.js
- src/pages/Applications/Components/Tools/useChangeFormikTools.js
- src/pages/Applications/CreateApplication.jsx
- src/pages/Applications/EditApplication.jsx
- src/pages/Applications/useApplicationInitialValues.jsx
- feat: creating/updating application
> feat: creating/updating application

- src/App.jsx
- src/api/applications.js
- src/pages/Applications/Components/Applications/ApplicationView.jsx
- src/pages/Applications/Components/Applications/DeleteVersionButton.jsx
- src/pages/Applications/Components/Applications/EditApplicationTabBar.jsx
- src/pages/Applications/Components/Applications/SaveNewVersionButton.jsx
- src/pages/Applications/Components/Applications/VersionSelect.jsx
- src/pages/Applications/Components/Applications/useDeleteVersion.js
- src/pages/Applications/Components/Applications/useSaveNewVersion.js
- src/pages/Applications/EditApplication.jsx
- src/pages/Prompts/Components/useDeleteVersion.js
- src/pages/Prompts/Components/useSaveNewVersion.js
- src/pages/hooks.jsx
- feat: application version list; save as version/delete version
> feat: application version list; save as version/delete version

- src/common/utils.jsx
- src/pages/Settings/CreatePersonalToken.jsx
- src/pages/Settings/components/PersonalTokenTable.jsx
- fix: token with expiration "never" disaplayed as "expired"
> fix: token with expiration "never" disaplayed as "expired"

- src/components/Categories.jsx
- src/pages/Applications/Latest.jsx
- src/pages/Applications/MyLiked.jsx
- src/pages/Applications/Top.jsx
- src/pages/Applications/Trending.jsx
- src/pages/Collections/Latest.jsx
- src/pages/Collections/MyLiked.jsx
- src/pages/Collections/Top.jsx
- src/pages/Collections/Trending.jsx
- src/pages/DataSources/Latest.jsx
- src/pages/DataSources/MyLiked.jsx
- src/pages/DataSources/Top.jsx
- src/pages/MyLibrary/AllStuffList.jsx
- src/pages/MyLibrary/ApplicationsList.jsx
- src/pages/MyLibrary/CollectionsList.jsx
- src/pages/MyLibrary/DataSourcesList.jsx
- src/pages/MyLibrary/PromptsList.jsx
- src/pages/MyLibrary/useLoadApplications.js
- src/pages/MyLibrary/useLoadDatasources.js
- src/pages/MyLibrary/useLoadPrompts.js
- src/pages/Prompts/Latest.jsx
- src/pages/Prompts/MyLiked.jsx
- src/pages/Prompts/Top.jsx
- src/pages/Prompts/Trending.jsx
- src/pages/hooks.jsx
- fix: filter tags by entity coverage in my libraries
> fix: filter tags by entity coverage in my libraries

- src/common/constants.js
- src/components/ChatBox/AIAnswer.jsx
- src/components/ChatBox/ApplicationAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/ToolAction.jsx
- src/components/DataCards.jsx
- src/pages/Applications/Components/Applications/ApplicationRightContent.jsx
> feat: application chat UI

- src/pages/Applications/Components/Applications/EditApplicationTabBar.jsx
- src/pages/Applications/Components/Tools/ToolCard.jsx
- src/pages/Prompts/Components/EditModeRunTabBarItems.jsx
- fix: adjust the buttons order of Prompts and Applications
> fix: adjust the buttons order of Prompts and Applications

- src/components/StickyTabs.jsx
> fix: change badge count bkg

- src/components/ChatBox/StyledComponents.jsx
- src/components/NavBar.jsx
- fix: truncate the breadcrumbs if the total length is more than 64 chars
> fix: truncate the breadcrumbs if the total length is more than 64 chars

- src/pages/Applications/Components/Applications/VersionSelect.jsx
- src/pages/Prompts/Components/Common.jsx
- src/pages/Prompts/Components/Form/VersionSelect.jsx
- fix: reduce padding in version select
> fix: reduce padding in version select

- src/pages/Applications/Components/Applications/DeleteVersionButton.jsx
- src/pages/Applications/Components/Applications/EditApplicationTabBar.jsx
- src/pages/Applications/Components/Applications/SaveNewVersionButton.jsx
- src/pages/Applications/Components/Applications/useDeleteVersion.js
- fix: delete application version updating issue
> fix: delete application version updating issue

- src/components/NavBar.jsx
- src/pages/Collections/CollectionDetail.jsx
- src/pages/Prompts/Components/AddToCollectionDialog.jsx
fix: AddToCollectionDialog misalignment issue
> fix: AddToCollectionDialog misalignment issue

- src/MainTheme.js
- src/components/ChatBox/AIAnswer.jsx
- src/components/HeaderSplitButton.jsx
- src/pages/Applications/Components/Tools/ToolCard.jsx
- fix: background color of alita answer
> fix: background color of alita answer

- src/pages/Applications/Components/Applications/ApplicationCreateForm.jsx
- src/pages/Applications/Components/Tools/ToolForm.jsx
- src/pages/Applications/CreateApplication.jsx
- src/pages/Applications/EditApplication.jsx
- fix: Application Instructions accordion not saving state (open/close) between adding actions
> fix: Application Instructions accordion not saving state (open/close) between adding actions

- src/App.jsx
- fix: permissions not updated when switching project
> fix: permissions not updated when switching project

- src/pages/DataSources/Components/Datasources/DeduplicateResultContent.jsx
- src/pages/DataSources/Components/Datasources/SearchResultContent.jsx
- fix: datasource chatting references wrap lines
> fix: datasource chatting references wrap lines

- src/pages/DataSources/Components/Datasources/DeduplicatePanel.jsx
- src/pages/DataSources/Components/Datasources/SearchPanel.jsx
- src/pages/hooks.jsx
- fix: completion result height issue
> fix: completion result height issue

- src/pages/Applications/Components/Applications/useSaveVersion.js
- fix: add owner id for updating application
> fix: add owner id for updating application

- src/components/Categories.jsx
- src/slices/prompts.js
- fix: add entity_coverage for collections page tags
> fix: add entity_coverage for collections page tags

- src/components/ChatBox/ToolAction.jsx
- feat: add copy button for action required
> feat: add copy button for action required

- src/common/utils.jsx
- src/pages/DataSources/Components/Datasets/DataSet.jsx
- src/pages/DataSources/Components/Sources/FormikInput.jsx
- src/pages/DataSources/Components/Sources/Source.jsx
- src/pages/DataSources/Components/Sources/SourceQTest.jsx
- src/pages/DataSources/constants.js
- feat: datasource QTest dataset
> feat: datasource QTest dataset

- src/pages/DataSources/Components/Datasets/DataSet.jsx
- src/pages/DataSources/Components/Sources/SourceQTest.jsx
- fix: change QTtest project_id into qtest_project_id
> fix: change QTtest project_id into qtest_project_id

- src/pages/DataSources/Components/Sources/SourceQTest.jsx
> fix: QTest project id label

- src/pages/DataSources/Components/Datasets/DataSet.jsx
- fix: dataset schema validating stop submission
> fix: dataset schema validating stop submission

- src/common/constants.js
- src/common/eventEmitter.js
- src/common/utils.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatSearchBar.jsx
- src/components/ChatSuggestionList.jsx
- src/components/useChatSearch.jsx
- src/pages/Chat/Chat.jsx
- src/pages/Chat/Components/ChatBox.jsx
- src/pages/Chat/Components/NewConversationSettings.jsx
- src/pages/Chat/Components/ParticipantItem.jsx
- src/pages/Chat/Components/ParticipantSettings.jsx
- src/pages/Chat/Components/Participants.jsx
- src/pages/Chat/Components/ParticipantsDropdown.jsx
- src/pages/Chat/Components/SuggestedParticipants.jsx
- src/pages/Chat/Components/useInputKeyDownHandler.jsx
- feat: add chat participant by search
> feat: add chat participant by search

- src/components/ChatBox/ChatBox.jsx
- src/pages/Chat/Components/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- fix: the regenerate button is not disabled when generating
> fix: the regenerate button is not disabled when generating

- src/pages/Collections/ModeratorToolBar.jsx
- src/pages/Prompts/Components/ModeratorToolBar.jsx
- fix: moderation space buttons are disabled
> fix: moderation space buttons are disabled

- src/pages/Chat/Chat.jsx
- src/pages/Chat/Components/Conversations.jsx
- fix: Chat conversation edit issue
> fix: Chat conversation edit issue

- src/components/ChatBox/ChatBox.jsx
- src/pages/Chat/Components/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- fix: should disable regenerate when streaming
> fix: should disable regenerate when streaming

- src/common/constants.js
- src/components/ChatBox/AgentException.jsx
- src/components/ChatBox/ApplicationAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/hooks.js
- src/components/DotMenu.jsx
- src/pages/Applications/Components/Applications/ApplicationRightContent.jsx
- src/pages/Applications/EditApplication.jsx
- feat: application predict UI
> feat: application predict UI

- src/MainTheme.js
- src/common/constants.js
- src/components/ChatBox/ApplicationAnswer.jsx
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/UserMessage.jsx
- src/components/ChatBox/hooks.js
- src/components/ChatSuggestionList.jsx
- src/components/useChatSearch.jsx
- src/pages/Chat/Chat.jsx
- src/pages/Chat/Components/ChatBox.jsx
- src/pages/Chat/Components/ChatBoxHeader.jsx
- src/pages/Chat/Components/Conversations.jsx
- src/pages/Chat/Components/ConverstionItem.jsx
- src/pages/Chat/Components/DeleteParticipantButton.jsx
- src/pages/Chat/Components/NewConversationSettings.jsx
- src/pages/Chat/Components/ParticipantItem.jsx
- src/pages/Chat/Components/ParticipantSettings.jsx
- src/pages/Chat/Components/Participants.jsx
- src/pages/Chat/Components/SuggestedParticipants.jsx
- src/pages/Chat/Components/useInputKeyDownHandler.jsx
- src/pages/Chat/Components/useResetCreateFlag.js
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- feat: chat messages interactions
> feat: chat messages interactions

- src/components/ChatBox/AgentException.jsx
- src/components/ChatBox/ApplicationAnswer.jsx
- src/components/StyledTabs.jsx
- src/pages/Chat/Components/DatasourceSettings.jsx
- src/pages/Chat/Components/NewConversationSettings.jsx
- feat: new conversation datasource settings
> feat: new conversation datasource settings

- src/components/Markdown.jsx
- src/pages/DataSources/Components/Datasources/SearchResultContent.jsx
- fix: data source search crashes with exception of toLowerCase
> fix: data source search crashes with exception of toLowerCase

- src/pages/Chat/Chat.jsx
- src/pages/Chat/Components/ConverstionItem.jsx
- src/pages/Chat/Components/DatasourceSettings.jsx
- src/pages/Chat/Components/NewConversationSettings.jsx
- src/pages/Chat/Components/ParticipantItem.jsx
- src/pages/Chat/Components/ParticipantSettings.jsx
- src/pages/Chat/Components/Participants.jsx
- src/pages/Prompts/Components/Form/InputVersionDialog.jsx
- feat: allow to select versions when the participant has multiple versions
> feat: allow to select versions when the participant has multiple versions

- package-lock.json
- package.json
- src/common/constants.js
- src/components/ChatBox/ChatBox.jsx
- src/components/ChatBox/hooks.js
- src/pages/Chat/Chat.jsx
- src/pages/Chat/Components/ChatBox.jsx
- src/pages/DataSources/Components/Datasources/ChatPanel.jsx
- src/pages/Prompts/Components/Form/Messages.jsx
- feat: integrate chat predict event and use uuid v4 as message id
> feat: integrate chat predict event and use uuid v4 as message id

- src/components/ChatBox/ApplicationAnswer.jsx
- src/pages/DataSources/Components/Datasets/DataSet.jsx
- fix: wrong background color of Application chat answer; 
- fix: avoid querying status of datasets which are done
> fix: wrong background color of Application chat answer; dataset status query issue

- src/pages/Applications/Components/Applications/ApplicationDetailToolbar.jsx
- src/pages/Applications/EditApplication.jsx
- src/pages/DataSources/Components/Datasources/DataSourceDetailToolbar.jsx
- feat: add datasource/application into collection UI
> feat: add datasource/application into collection UI
